name: app
description: "Sahajmobile customer app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.1
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.7
  dio: ^5.9.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  get_it: ^8.2.0
  injectable: ^2.5.2
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  http: ^1.5.0
  logger: ^2.6.2
  shared_preferences: ^2.5.3
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  flutter_flavor: ^3.1.4
  flutter_screenutil: ^5.9.3
  simple_animations: ^5.2.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  flutter_gen_runner: ^5.12.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/animations/
